### ISSUE TITLE
Add labels for CLA signing status on community contributions

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitbot#53]
### Problem to solve

The ongoing work in https://github.com/gitpod-io/gitpod/pull/6318 will configure an automated CLA signing process so that community contributors can go through a self-serve process to sign our CLA. Cc @mads-hartmann @meysholdt 

While the process in https://github.com/gitpod-io/gitpod/pull/6318 is still in the works, it's worth mentioning that CLA signing status could be still not visible when going through the PRs (pull requests) list, etc.

### Proposal

Introduce labels to indicate whether the CLA signing process is pending or accepted.

For example we could use two group labels like `cla: pending` and `cla: accepted`. 🏷️ 

This can help bring more visibility on the CLA signing status. For example, check out https://github.com/gitpod-io/gitpod/pull/6031 to see whether it's clear if the CLA has been accepted.

**Comment by mads-hartmann** [comment]
I understand the current situtation is confusing and getting the automation in place is taking much longer than expected due pending on feedback from legal 😔

We could manually add the labels now while we wait for automation but I would rather not as it will require additional work[^1] to automate the labels going forward and I don't believe they provide enough value once the automation is in place to be prioritised above other work at the moment.

I see two use-case for the labels

1. (as you stated) improving the visibility of whether or not the CLA is signed for a given PR
2. We could take the label into account in our PR automatic merge process (e.g. only merge approved PRs where the CLA is signed)

For (1) it will be quite clear going forward if the CLA is signed as it will be visible in the comment thread ([see demo gif](https://github.com/cla-assistant/github-action#demo-for-step-2-and-3)). For (2) we can work around it by not approving PRs that don't have the CLA signed (as we do now) and based on (1) it should be easy for reviewers to tell if it is signed.

So while I do see the value in having the labels I don't believe it is worth the effort at the moment. I'm closing the issue, but feel free to reopen if you feel strongly otherwise ☺️

[^1]:  Automatically applying the label won't be trivial as the signatures will be stored in https://github.com/gitpod-io/cla and the [cla-assistant/github-action](https://github.com/cla-assistant/github-action) doesn't provide that feature out of the box so we'd need to write some automation ourselves to apply the label.

**Comment by gtsiolis** [comment]
Thanks for taking a look @mads-hartmann!

I'd expect this feature request to become relevant again in the near future once we establish more mature workflows around community contributions and triage operations for issues and pull requests. 🗺️ 

We could keep this issue open for tracking this but it's also fine to close this for now. 📕 

In the meantime, I've added two new labels so we can manually attach these in case these can help. For example, see https://github.com/gitpod-io/gitpod/pull/6907#event-5674196863.
- `cla: pending`
- `cla: accepted`

I'll cross post this in slack internally for visibility and feedback.

Next steps could include adding some some documentation bits describing usage and guidelines for using these two new labels if needed but this is out of the scope of this issue. 🔖
